sonar.projectKey=ahu-services_cs-image-tools
sonar.organization=ahu-services

sonar.sources=entrypoint.py,health_check.py,Dockerfile
sonar.tests=tests

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
